require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'kartoffellist' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'kartoffellistTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  def add_flipper_pods!
    version = '~> 0.33.1'
    pod 'FlipperKit', version, :configuration => 'Debug'
    pod 'FlipperKit/FlipperKitLayoutPlugin', version, :configuration => 'Debug'
    pod 'FlipperKit/SKIOSNetworkPlugin', version, :configuration => 'Debug'
    pod 'FlipperKit/FlipperKitUserDefaultsPlugin', version, :configuration => 'Debug'
    pod 'FlipperKit/FlipperKitReactPlugin', version, :configuration => 'Debug'
  end
  # Post Install processing for Flipper
  def flipper_post_install(installer)
    installer.pods_project.targets.each do |target|
      if target.name == 'YogaKit'
        target.build_configurations.each do |config|
          config.build_settings['SWIFT_VERSION'] = '4.1'
        end
      end
    end
  end

end